name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Le pipeline se déclenche sur les push vers la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ========== BACKEND ==========
      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app ./springboot/app

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app

      # ========== FRONTEND ==========
      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-app ./angular-app

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app

  test-application:
    runs-on: ubuntu-latest
    needs: build-and-push   # Ce job dépend du build-and-push

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Lancer l'application avec docker-compose
      - name: Run docker-compose
        run: docker-compose up -d

      # Étape 3 : Vérifier les conteneurs en cours
      - name: Running containers
        run: docker ps

      # Étape 4 : Afficher les logs
      - name: Show logs
        run: docker-compose logs

